#!/bin/sh

# Key directories
SRCBASE=/home/boyd/src
CPYDIR=$SRCBASE/cvx.dist
ARCHIVE=file://$SRCBASE/svn/cvx
DSTDIR=/home/boyd/WWW/cvx

# Grab a clean copy of the current version
rm -rf $CPYDIR
mkdir $CPYDIR
svn export $ARCHIVE $CPYDIR/cvx

# Compile the documentation
cd $CPYDIR/cvx/doc
latex  cvx_usrguide
latex  cvx_usrguide
bibtex cvx_usrguide
latex  cvx_usrguide
latex  cvx_usrguide
latex  cvx_usrguide
dvips  cvx_usrguide
ps2pdf cvx_usrguide.ps

# Set the permissions
chgrp -fR research $CPYDIR 
chmod -fR a+r,gu+w $CPYDIR
find $CPYDIR -type d -exec chmod g+s {} \;

# Create the archives
cd $CPYDIR
rm $DSTDIR/cvx.{tar.gz,zip}
tar cvfz $DSTDIR/cvx.tar.gz cvx/*.{m,txt} cvx/doc/*.pdf cvx/{@double,examples,functions,keywords,lib,matlab6,sedumi,sets,structures}
zip -r -9 $DSTDIR/cvx.zip cvx/*.{m,txt} cvx/doc/*.pdf cvx/{@double,examples,functions,keywords,lib,matlab6,sedumi,sets,structures}

# Copy the documentation over
cp $CPYDIR/cvx/doc/*.pdf $DSTDIR

# Update the index file
MYDATE=`date`
MYZIP=`du --si $DSTDIR/cvx.zip | sed 's@\s.*@@'`
MYTAR=`du --si $DSTDIR/cvx.tar.gz | sed 's@\s.*@@'`
sed "s@___DATE___@$MYDATE@;s@___ZIP___@$MYZIP@;s@___TAR___@$MYTAR@" $CPYDIR/cvx/doc/index.html > $DSTDIR/index.html

# Set the permissons at the destination
chgrp -fR research $DSTDIR
chmod -fR a+r,ug+w $DSTDIR

# Remove the working directory
cd $SRCBASE
rm -rf $CPYDIR

