#!/bin/sh

# Version number
MYVERSION=1.1

# Key directories
SRC=`pwd | sed 's@/doc$@@'`
svn update $SRC
SVN=`svn info | grep '^Repository Root: ' | sed 's/^Repository Root: *//'`

# Key subdirectories / sub-repositories
DST=$SRC/WWW
CPY=$SRC/tmp
CVX=$CPY/cvx
TEX=$CPY/doc
TRU=$SVN/trunk
EXA=$SVN/examples
DOC=$SVN/doc
TAR=$DST/cvx.tar.gz
ZIP=$DST/cvx.zip

# Build number
MYBUILD=`svn info $TRU | grep "^Last Changed Rev" | sed "s/[^0-9]*//"`
MYTDATE=`date +"%B %Y"`
VERSED="s@___VERSION___@$MYVERSION@;s@___BUILD___@$MYBUILD@;s@___TDATE___@$MYTDATE@;"
TEXSED="s@cvxver{...@cvxver{$MYVERSION@;s@cvxbuild{...@cvxbuild{$MYBUILD@"

/bin/echo -n Preparing work and staging directories...
rm -rf $DST $CPY
mkdir -p $DST $CPY
/bin/echo done.

/bin/echo -n Retrieving latest sources...
svn export $TRU $CVX          >/dev/null
svn export $EXA $CVX/examples >/dev/null
svn export $EXA $DST/examples >/dev/null
svn export $DOC $TEX          >/dev/null
/bin/echo done.
# Insert version information into the version file and docs
cd $CVX
sed "$VERSED" cvx_version.m > cvx_version.m.new
mv -f cvx_version.m.new cvx_version.m
cd $TEX
sed "$TEXSED" cvx_usrguide.tex > cvx_usrguide.tex.new
mv -f cvx_usrguide.tex.new cvx_usrguide.tex

/bin/echo -n Compiling the documentation...
latex        cvx_usrguide >/dev/null </dev/null
latex        cvx_usrguide >/dev/null </dev/null
bibtex       cvx_usrguide >/dev/null
makeindex -q cvx_usrguide >/dev/null
latex        cvx_usrguide >/dev/null </dev/null
latex        cvx_usrguide >/dev/null </dev/null
dvips -q     cvx_usrguide >/dev/null
ps2pdf       cvx_usrguide.ps
cp cvx_usrguide.pdf $CVX
cp cvx_usrguide.pdf $DST
/bin/echo done.

/bin/echo -n Creating the archives...
cd $CPY
chmod -fR a+r,gu+w cvx
find cvx -type d -exec chmod g+s {} \;
tar cfz $TAR cvx >/dev/null
zip -r -9 $ZIP cvx >/dev/null
/bin/echo done.

/bin/echo -n Updating the web pages...
MYDATE=`date`;
MYZIP=`du -h $ZIP | sed 's@\([0-9.]*.\).*@\1B@'`
MYTAR=`du -h $TAR | sed 's@\([0-9.]*.\).*@\1B@'`
MYPDF=`du -h $DST/cvx_usrguide.pdf | sed 's@\([0-9.]*.\).*@\1B@'`
SEDSTR="$VERSED;s@___DATE___@$MYDATE@;s@___ZIP___@$MYZIP@;s@___TAR___@$MYTAR@;s@___PDF___@$MYPDF@"
sed "$SEDSTR" $TEX/citing.html     > $DST/citing.html
sed "$SEDSTR" $TEX/contact.jemdoc  > $DST/contact.jemdoc
sed "$SEDSTR" $TEX/download.jemdoc > $DST/download.jemdoc
sed "$SEDSTR" $TEX/history.jemdoc  > $DST/history.jemdoc
sed "$SEDSTR" $TEX/index.jemdoc    > $DST/index.jemdoc
sed "$SEDSTR" $TEX/license.jemdoc  > $DST/license.jemdoc
cp -f $TEX/MENU $TEX/*.{gif,png,conf,css} $DST
cd $DST
jemdoc -c jemdoc.conf *.jemdoc
/bin/echo done.

/bin/echo -n Cleaning up...
chmod -fR a+r,ug+w $DST
rm -rf $CPY
/bin/echo done.
/bin/echo Staging directory $DST completed.

