#!/bin/sh

# Key directories
SRCBASE=/home/boyd/src
CPYDIR=$SRCBASE/cvx.dist
ARCHIVE=file://$SRCBASE/svn/cvx/branches/transpose
EXAMPLES=file://$SRCBASE/svn/cvx/examples
DOCDIR=file://$SRCBASE/svn/cvx/doc
DSTDIR=/home/boyd/WWW/cvx

# Grab a clean copy of the current version
rm -rf $CPYDIR
mkdir $CPYDIR
svn export $ARCHIVE $CPYDIR/cvx
svn export $EXAMPLES $CPYDIR/cvx/examples
svn export $DOCDIR $CPYDIR/cvx/doc

# Compile the documentation
cd $CPYDIR/cvx/doc
latex  cvx_usrguide
latex  cvx_usrguide
bibtex cvx_usrguide
latex  cvx_usrguide
latex  cvx_usrguide
latex  cvx_usrguide
dvips  cvx_usrguide
ps2pdf cvx_usrguide.ps

# Set the permissions
chgrp -fR research $CPYDIR 
chmod -fR a+r,gu+w $CPYDIR
find $CPYDIR -type d -exec chmod g+s {} \;

# Create the archives
cd $CPYDIR
rm $DSTDIR/cvx.{tar.gz,zip}
tar cvfz $DSTDIR/cvx.tar.gz cvx/*.{m,txt} cvx/doc/*.pdf cvx/{@double,examples,functions,keywords,lib,matlab6,sedumi,sets,structures}
zip -r -9 $DSTDIR/cvx.zip cvx/*.{m,txt} cvx/doc/*.pdf cvx/{@double,examples,functions,keywords,lib,matlab6,sedumi,sets,structures}
cd cvx
tar cvf $DSTDIR/cvx-examples.tar examples

# Copy the documentation over and extract examples
cd $DSTDIR
cp $CPYDIR/cvx/doc/*.pdf .
rm -rf examples
tar xvf cvx-examples.tar
rm -rf cvx-examples.tar

# Update the index file and history file
MYDATE=`date`
MYZIP=`du --si $DSTDIR/cvx.zip | sed 's@\s.*@@'`
MYTAR=`du --si $DSTDIR/cvx.tar.gz | sed 's@\s.*@@'`
MYPDF=`du --si $DSTDIR/cvx_usrguide.pdf | sed 's@\s.*@@'`
sed "s@___DATE___@$MYDATE@;s@___ZIP___@$MYZIP@;s@___TAR___@$MYTAR@;s@___PDF___@$MYPDF@" $CPYDIR/cvx/doc/index.html > $DSTDIR/index.html
sed "s@___DATE___@$MYDATE@" $CPYDIR/cvx/doc/history.html > $DSTDIR/history.html
cp -f $CPYDIR/cvx/doc/checked_by_tidy.gif $DSTDIR
cp -f $CPYDIR/cvx/doc/valid-xhtml10.png $DSTDIR

# Set the permissons at the destination
chgrp -fR research $DSTDIR
chmod -fR a+r,ug+w $DSTDIR

# Remove the working directory
cd $SRCBASE
rm -rf $CPYDIR

