#! /bin/sh

# Key directories
SRCBASE=`pwd | sed 's@/doc$@@'`
SRC=$SRCBASE/dist
HST=kona.stanford.edu
DST=/home/boyd/src/cvx

echo Updating: $SRC --\> $DST
rsync -rlv --delete -e ssh $SRC/ $HST:$DST/
ssh $HST chgrp -fR research $DST
ssh $HST chmod -fR g+w $DST


