#! /bin/sh

# Key directories
SRCBASE=`pwd | sed 's@/doc$@@'`
WWWDIR=$SRCBASE/WWW
DSTDIR=$SRCBASE/dist
WWWDST=cardinal.stanford.edu:~boyd/WWW/cvx
BYDDST=kona.stanford.edu:~boyd/WWW/cvx

echo Updating: $WWWDIR --\> $WWWDST
rsync -rlv --delete -e ssh $WWWDIR/ $WWWDST/
echo Updating: $WWWDIR --\> $BYDDST
rsync -rlv --delete -e ssh $WWWDIR/ $BYDDST/

