#! /bin/sh

# Key directories
SRCBASE=`pwd | sed 's@/doc$@@'`
WWWDIR=$SRCBASE/WWW
DSTDIR=$SRCBASE/dist
WWWDST=cardinal.stanford.edu:~boyd/WWW/cvx
BYDDST=kona.stanford.edu:~boyd/WWW/cvx

echo Updating: $WWWDIR --\> $WWWDST
rsync -rlv --delete --exclude cvx.zip --exclude cvx.tar.gz -e ssh $WWWDIR/ $WWWDST/
scp $WWWDIR/{cvx.zip,cvx.tar.gz} $WWWDST/
echo Updating: $WWWDIR --\> $BYDDST
rsync -rlv --delete --exclude cvx.zip --exclude cvx.tar.gz -e ssh $WWWDIR/ $BYDDST/
scp $WWWDIR/{cvx.zip,cvx.tar.gz} $BYDDST/

