function cvx_warn_strict( op )
warning( 'CVX:StrictInequalities', [ ...
'The use of a strict inequality "%s" in CVX is strongly discouraged. CVX\n', ...
'will interpret this inequality identically to its non-strict counterpart "%s="\n', ...
'and the solvers will do so as well. Please see the section ', ...
'<a href="http://web.cvxr.com/cvx/doc/dcp.html#strict-inequalities">Strict inequalities</a>\n', ...
'in the CVX Users'' Guide for more information.' ], op, op );
